server:
  port: 8080

spring:
  application:
    name: fleet-management

  profiles:
    active: local

  # CONFIG GLOBALE (Surchargeable par env vars)
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:yowyob}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    pool:
      enabled: true
      initial-size: 2
      max-size: 10

  # Liquibase par défaut (sera surchargé en local)
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: fleet
    liquibase-schema: public # Schéma où se trouve la table DATABASECHANGELOG
    enabled: true
    contexts: ${spring.profiles.active}

  sql:
    init:
      mode: never

  # KAFKA 
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    consumer:
      group-id: fleet-management-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# CUSTOM CONFIG 
application:
  external:
    stock-service-url: http://${EXTERNAL_HOST:localhost}:8081
    vehicle-service-url: https://vehicule-service.pynfi.com
  auth:
    mode: remote
    url: https://auth-service.pynfi.com

  kafka:
    topics:
      product-events: test-topic

management:
  endpoints:
    web:
      exposure:
        include: ["health","info","prometheus"]
  endpoint:
    health:
      show-details: "always"
      probes:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      stock-service:
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        slidingWindowSize: 5

---
# ==========================================
# LOCAL CONFIGURATION (Docker Local)
# ==========================================
spring:
  config:
    activate:
      on-profile: local
  
  # R2DBC (Application Runtime) -> Pointe vers yowyob_db
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/yowyob_db
    username: fleet_admin
    password: fleet_password

  # JDBC (Liquibase Migration) -> Pointe vers yowyob_db 
  datasource:
    url: jdbc:postgresql://localhost:5432/yowyob_db
    username: fleet_admin
    password: fleet_password
    driver-class-name: org.postgresql.Driver

---
# ==========================================
# REMOTE CONFIGURATION (Server)
# ==========================================
spring:
  config:
    activate:
      on-profile: remote
  
  # En remote, on suppose que les vars d'environnement pilotent tout
  # On désactive l'init SQL destructif par sécurité
  sql:
    init:
      mode: never