server:
  port: 8080

spring:
  application:
    name: fleet-management

  # THE "TOGGLE": Change 'local' to 'remote' to switch databases
  profiles:
    active: local 
    
  docker:
    compose:
      enabled: false

  # POSTGRESQL (R2DBC)
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:yowyob}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  sql:
    init:
      mode: always

  # REDIS CLUSTER 
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:7000}
      password: ${REDIS_PASSWORD:password}
      cluster:
        enabled: false

  # KAFKA 
  kafka:
    bootstrap-servers:  ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    consumer:
      group-id: fleet-management-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# CUSTOM CONFIG 
application:
  external:
    stock-service-url: http://168.119.122.86:8081
    
    vehicle-service-url: https://vehicule-service.pynfi.com
    
  auth:
    mode: remote # Mettez 'remote' pour tester le vrai service TraMaSys et 'fake' pour la fausse authentification en test
    url: https://auth-service.pynfi.com # URL de la doc TraMaSys

  kafka:
    topics:
      product-events: test-topic

management:
  endpoints:
    web:
      exposure:
        include: ["health","info","prometheus"]
  endpoint:
    health:
      show-details: "always"
      probes:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

 

# RESILIENCE4J 
resilience4j:
  circuitbreaker:
    instances:
      stock-service:
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        slidingWindowSize: 5

---
# LOCAL CONFIGURATION
spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/yowyob_db
    username: fleet_admin
    password: fleet_password
  sql:
    init:
      mode: never

---
# REMOTE CONFIGURATION (Server)
r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:yowyob}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
sql:
  init:
    mode: never