server:
  port: 8080

spring:
  application:
    name: fleet-management
  
  profiles:
    active: local

  # R2DBC (Application Runtime)
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/yowyob_db
    username: fleet_admin
    password: fleet_password
    pool:
      enabled: true
      initial-size: 2
      max-size: 10

  # JDBC (Liquibase Migration)
  datasource:
    url: jdbc:postgresql://localhost:5432/yowyob_db
    username: fleet_admin
    password: fleet_password
    driver-class-name: org.postgresql.Driver

  # LIQUIBASE
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
    liquibase-schema: public
    enabled: true
    contexts: local

  # REDIS
  data:
    redis:
      host: localhost
      port: 6379
      password: "" 

  # KAFKA
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: fleet-management-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  docker:
    compose:
      enabled: false

# CONFIG METIER
application:
  external:
    vehicle-service-url: https://vehicule-service.pynfi.com
  auth:
    mode: remote 
    url: https://auth-service.pynfi.com

  # Kafka topics
  kafka:
    topics:
      # product-events removed
      geofence-alerts: geofence-alerts-topic # Anticipation pour le futur

# MONITORING
management:
  endpoints:
    web:
      exposure:
        include: ["health","info","prometheus"]
  endpoint:
    health:
      show-details: "always"
      probes:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# Resilience4j nettoy√© (plus de stock-service)
resilience4j:
  circuitbreaker:
    instances: {}